### ISSUE TITLE
Is there an iterate function?

### ISSUE THREAD

**Issue by hiqsociety** [kampersanda/poplar-trie#3]
1. Is there an iterate function?
2. any update on the delete operation?

**Comment by kampersanda** [comment]
1. No. Poplar-trie cannot support an efficient iteration due to the hash-based approach.
2. Please set an invalid value as a deletion flag.

**Comment by hiqsociety** [comment]
invalid value as deletion flag... will this be truly fixed?

**Comment by kampersanda** [comment]
1. In principle, it can be implemented on Poplar. But since the running time will be very slow, there is no plan to implement it at this moment. 
2. Yes. Poplar cannot release unused memory.

**Comment by hiqsociety** [comment]
2. can you implement delete function? without it, is a bit strange. i think there will be an overhead associated with this delete function but maybe then create another repo just for this?

**Comment by kampersanda** [comment]
The deletion can be easily implemented without touching the inner of the library.
For example, when the value type is `int` and the invalid value is `-1`, it can be implemented as follows.
```
int* ptr = map.update(del_key);
*ptr = -1;
```

**Comment by hiqsociety** [comment]
i'm not proficient in c++ but only knows golang.
possible for you to show an example for []byte type? map of []byte, []byte 

would love to see how to implement golang binding after this. if you can do so will be great, else i will try the golang binding for this. i'm not good with cpp so will take some time.

**Comment by kampersanda** [comment]
When storing dynamic arrays (like slice in Go) as values of Poplar-trie, you should store pointers to the arrays in the trie and maintain the arrays separately.

**Comment by hiqsociety** [comment]
great. i understand now. thx. appreciate this.
